# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'caculator_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(431, 247)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.two = QtWidgets.QPushButton(self.centralwidget)
        self.two.setObjectName("two")
        self.gridLayout.addWidget(self.two, 4, 1, 1, 1)
        self.six = QtWidgets.QPushButton(self.centralwidget)
        self.six.setObjectName("six")
        self.gridLayout.addWidget(self.six, 3, 2, 1, 1)
        self.three = QtWidgets.QPushButton(self.centralwidget)
        self.three.setObjectName("three")
        self.gridLayout.addWidget(self.three, 4, 2, 1, 1)
        self.divide = QtWidgets.QPushButton(self.centralwidget)
        self.divide.setObjectName("divide")
        self.gridLayout.addWidget(self.divide, 1, 3, 1, 1)
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setObjectName("add")
        self.gridLayout.addWidget(self.add, 5, 3, 1, 1)
        self.one = QtWidgets.QPushButton(self.centralwidget)
        self.one.setObjectName("one")
        self.gridLayout.addWidget(self.one, 4, 0, 1, 1)
        self.mutiply = QtWidgets.QPushButton(self.centralwidget)
        self.mutiply.setObjectName("mutiply")
        self.gridLayout.addWidget(self.mutiply, 3, 3, 1, 1)
        self.sub = QtWidgets.QPushButton(self.centralwidget)
        self.sub.setObjectName("sub")
        self.gridLayout.addWidget(self.sub, 4, 3, 1, 1)
        self.zero = QtWidgets.QPushButton(self.centralwidget)
        self.zero.setObjectName("zero")
        self.gridLayout.addWidget(self.zero, 5, 0, 1, 1)
        self.equal = QtWidgets.QPushButton(self.centralwidget)
        self.equal.setObjectName("equal")
        self.gridLayout.addWidget(self.equal, 5, 2, 1, 1)
        self.dot = QtWidgets.QPushButton(self.centralwidget)
        self.dot.setObjectName("dot")
        self.gridLayout.addWidget(self.dot, 5, 1, 1, 1)
        self.five = QtWidgets.QPushButton(self.centralwidget)
        self.five.setObjectName("five")
        self.gridLayout.addWidget(self.five, 3, 1, 1, 1)
        self.four = QtWidgets.QPushButton(self.centralwidget)
        self.four.setObjectName("four")
        self.gridLayout.addWidget(self.four, 3, 0, 1, 1)
        self.nine = QtWidgets.QPushButton(self.centralwidget)
        self.nine.setObjectName("nine")
        self.gridLayout.addWidget(self.nine, 1, 2, 1, 1)
        self.eight = QtWidgets.QPushButton(self.centralwidget)
        self.eight.setObjectName("eight")
        self.gridLayout.addWidget(self.eight, 1, 1, 1, 1)
        self.seven = QtWidgets.QPushButton(self.centralwidget)
        self.seven.setObjectName("seven")
        self.gridLayout.addWidget(self.seven, 1, 0, 1, 1)
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.result.setFont(font)
        self.result.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.result.setTextFormat(QtCore.Qt.PlainText)
        self.result.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.result.setObjectName("result")
        self.gridLayout.addWidget(self.result, 0, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 431, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Caculator 我的计算器"))
        self.two.setText(_translate("MainWindow", "2"))
        self.six.setText(_translate("MainWindow", "6"))
        self.three.setText(_translate("MainWindow", "3"))
        self.divide.setText(_translate("MainWindow", "/"))
        self.add.setText(_translate("MainWindow", "+"))
        self.one.setText(_translate("MainWindow", "1"))
        self.mutiply.setText(_translate("MainWindow", "*"))
        self.sub.setText(_translate("MainWindow", "-"))
        self.zero.setText(_translate("MainWindow", "0"))
        self.equal.setText(_translate("MainWindow", "="))
        self.dot.setText(_translate("MainWindow", "."))
        self.five.setText(_translate("MainWindow", "5"))
        self.four.setText(_translate("MainWindow", "4"))
        self.nine.setText(_translate("MainWindow", "9"))
        self.eight.setText(_translate("MainWindow", "8"))
        self.seven.setText(_translate("MainWindow", "7"))
        self.result.setText(_translate("MainWindow", "0"))
